apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "cicd-tools",
      "kind": "DeploymentConfig"}]'
  name: 
spec:
  source:
    git:
      ref: master
      uri: http://github.com/hodrigohamalho/rhforum.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
